import AppKit
import Combine

struct NewClipData {
    let type: ClipType
    let text: String?
    let imageData: Data?
    let filePath: String?
    let appBundleID: String?
    let appName: String?
}

// Types UTI à ignorer (mots de passe, données temporaires, artefacts système)
private let ignoredTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "com.1password.item-data",
    "RoboFormData",
    "com.lastpass.lpdefaulttype"
]

final class ClipboardMonitor {
    var onNewItem: ((NewClipData) -> Void)?

    private var timer: Timer?
    private var lastChangeCount: Int
    private var ignoredBundleIDs: Set<String> = []

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func ignore(bundleID: String) {
        ignoredBundleIDs.insert(bundleID)
    }

    private func checkPasteboard() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let sourceApp = NSWorkspace.shared.frontmostApplication
        let bundleID = sourceApp?.bundleIdentifier ?? ""

        guard !ignoredBundleIDs.contains(bundleID) else { return }
        guard bundleID != Bundle.main.bundleIdentifier else { return }

        extractContent(from: pasteboard, appBundleID: bundleID, appName: sourceApp?.localizedName)
    }

    private func extractContent(from pasteboard: NSPasteboard, appBundleID: String, appName: String?) {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return }

        // Ignore données sensibles (mots de passe, etc.)
        for item in items {
            for type in item.types {
                if ignoredTypes.contains(type.rawValue) { return }
            }
        }

        // Image
        if let tiff = pasteboard.data(forType: .tiff) {
            onNewItem?(.init(type: .image, text: nil, imageData: tiff, filePath: nil, appBundleID: appBundleID, appName: appName))
            return
        }
        if let png = pasteboard.data(forType: .png) {
            onNewItem?(.init(type: .image, text: nil, imageData: png, filePath: nil, appBundleID: appBundleID, appName: appName))
            return
        }

        // Fichiers
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           let first = urls.first {
            let path = first.path
            onNewItem?(.init(type: .file, text: path, imageData: nil, filePath: path, appBundleID: appBundleID, appName: appName))
            return
        }

        // Texte
        if let text = pasteboard.string(forType: .string) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return }
            let isURL = URL(string: text)?.scheme?.hasPrefix("http") == true
            onNewItem?(.init(type: isURL ? .url : .text, text: text, imageData: nil, filePath: nil, appBundleID: appBundleID, appName: appName))
        }
    }
}
